#!/bin/bash
#

if [[ "${1}" == "go" ]]; then
	ECHO=
	shift
else
	ECHO=echo
fi

DEST="${1}"
if [[ -z "${DEST}" ]]; then
	echo "*** please supply the custom_components directory"
	exit 1
fi	
if [[ ! -d "${DEST}" ]]; then
	echo "*** please make sure the destination directory exists"
	exit 1
fi

if [[ -n "${ECHO}" ]]; then
	echo "**** would run the following commands, use './install go $1' to do the work"
fi

${ECHO} cp -afv aarlo "${DEST}"
${ECHO} cp -afv alarm_control_panel "${DEST}"
${ECHO} cp -afv binary_sensor "${DEST}"
${ECHO} cp -afv camera "${DEST}"
${ECHO} cp -afv sensor "${DEST}"

