#!/bin/bash
#

if [[ "${1}" == "go" ]]; then
	ECHO=
	shift
else
	ECHO=echo
fi

DEST="${1}"
if [[ -z "${DEST}" ]]; then
	echo "*** please supply the home-assistant /config directory"
	exit 1
fi	
if [[ ! -d "${DEST}" ]]; then
	echo "*** please make sure the destination directory exists"
	exit 1
fi

if [[ -n "${ECHO}" ]]; then
	echo "**** would run the following commands, use './install go $1' to do the work"
fi

if [[ -f "${DEST}/custom_components/sensor/aarlo.py" ]]; then
	echo "****"
	echo "**** it looks like you have aarlo files using an old layout, you should remove it first with, see how by running:"
	echo "**** ./remove_old ${1}"
	echo "****"
	echo "****"
fi

#${ECHO} mkdir -p "${DEST}/www"
#${ECHO} cp -afv dist/hass-aarlo.js "${DEST}/www/aarlo-glance.js"

echo -- installing
${ECHO} mkdir -p "${DEST}/custom_components"
if [[ -n $(command -v fd) ]]; then
	fd -e py . -e json -e yaml custom_components --exec ${ECHO} cp -vf --parents {} "${DEST}" ;
else
	${ECHO} cp -afv custom_components/aarlo "${DEST}/custom_components"
fi
echo -- finished at "$(date '+%A at %H:%M:%S')"
