#!/bin/bash
#

DEST="${1}"
if [[ -z "${DEST}" ]]; then
	echo "*** please supply the custom_components directory"
	exit 1
fi	
if [[ ! -d "${DEST}" ]]; then
	echo "*** please make sure the destination directory exists"
	exit 1
fi

echo "**** please run the following commands to remove the old installation"
echo rm -v ${DEST}/alarm_control_panel/aarlo.py
echo rm -v ${DEST}/binary_sensor/aarlo.py
echo rm -v ${DEST}/camera/aarlo.py
echo rm -v ${DEST}/sensor/aarlo.py

