#!/bin/bash
#

DEST="${1}"
if [[ -z "${DEST}" ]]; then
	echo "*** please supply the home-assistant /config directory"
	exit 1
fi	
if [[ ! -d "${DEST}" ]]; then
	echo "*** please make sure the destination directory exists"
	exit 1
fi

echo "**** please run the following commands to remove the old installation"
echo rm -v ${DEST}/custom_components/alarm_control_panel/aarlo.py
echo rm -v ${DEST}/custom_components/binary_sensor/aarlo.py
echo rm -v ${DEST}/custom_components/camera/aarlo.py
echo rm -v ${DEST}/custom_components/sensor/aarlo.py

echo "**** please run the following commands to remove a newer installation"
echo rm -v ${DEST}/custom_components/aarlo/alarm_control_panel.py
echo rm -v ${DEST}/custom_components/aarlo/binary_sensor.py
echo rm -v ${DEST}/custom_components/aarlo/camera.py
echo rm -v ${DEST}/custom_components/aarlo/sensor.py

